---
name: lokum_app
description: Official mobile application for Bar Lokum.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.12.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/backgrounds/
    - assets/beer/
    - assets/cocktails/
    - assets/data/
    - assets/events/
    - assets/food/
    - assets/icons/
    - assets/logos/
    - assets/spirits/
    - assets/videos/
    - assets/wine/
